version: "3.8"

services:
  db:
    image: mysql
    container_name: db
    env_file:
      - .env
    command: --default-authentication-plugin=caching_sha2_password --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MAX_ALLOWED_PACKET: 256M
    volumes:
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
